### PR TITLE
added map and image modal to check-in list

### PR DESCRIPTION
**Pull request by nathanwerrede**
if there are no coordinates map modal is blank, will fix, but map and photo is shown

### CODE REVIEW

**Comment by cwguan** [comment]
image
Shouldn't there be one for your buddies? 

image
I think the button location should be moved to the bottom of all the info, having it in the middle makes it look out of place. Additionally, if we're going to display the image in the box, then it doesn't make sense to have a button for a modal for it

image
Also ran into this error

**Review by cwguan — DISMISSED** [review]
Left a comment on the PR!

**Comment by nathanwerrede** [comment]
Added location and photo to buddy check in, and removed location description from both check in fields. we used a button for the photo because some photos made the check in box really big

**Review by stevenphung96 — APPROVED** [review]
looks good

**Pull request merged**
